version: "3"

services:
  python:
    container_name: mkdocs
    image: python:3.13.0b1-alpine3.20
    volumes:
      - ./:/home
    working_dir: /home
    ports:
      - 8000:8000
    env_file:
      - ./env/.env

# make dockerfile
# RUN pip install mkdocs
# ENTRYPOINT mkdocs serve