version: "3"

services:
  python:
    container_name: mkdocs
    image: python:3.13.0b1-alpine3.20
    volumes:
      - ./:/home
    working_dir: /home/Pinting-Docs
    ports:
      - 8000:8000

# make dockerfile
# RUN pip install mkdocs
# ENTRYPOINT mkdocs serve

# pip install mkdocs && mkdocs serve -a 0.0.0.0:8000