version: "3"

services:
  mkdocs:
    container_name: mkdocs
    build: ./Pinting-Docs
    pull_policy: never
    volumes:
      - ./Pinting-Docs:/home
    working_dir: /home
    ports:
      - 8888:8888

# make dockerfile
# RUN pip install mkdocs
# ENTRYPOINT mkdocs serve

# pip install mkdocs && mkdocs serve -a 0.0.0.0:8888