site_name: Pinting
nav:
  - Home: index.md
  - architecture: 
    - 'DDD 설계': 'architecture/DDD.md'
  - Scrum:
    - 'index': 'scrums/scrum_0.md'
    - '2024.05.17.': 'scrums/2024.05.17.md'
    - '2024.05.18.': 'scrums/2024.05.18.md'
    - '2024.05.19.': 'scrums/2024.05.19.md'
    - '2024.05.20.': 'scrums/2024.05.20.md'
    - '2024.05.21.': 'scrums/2024.05.21.md'
    - '2024.05.22.': 'scrums/2024.05.22.md'
    - '2024.05.23.': 'scrums/2024.05.23.md'
    - '2024.05.24.': 'scrums/2024.05.24.md'
    - '2024.05.25.': 'scrums/2024.05.25.md'
    - '2024.05.26.': 'scrums/2024.05.26.md'
    - '2024.05.27.': 'scrums/2024.05.27.md'
    - '2024.05.28.': 'scrums/2024.05.28.md'
    - '2024.05.29.': 'scrums/2024.05.29.md'
    - '2024.05.30.': 'scrums/2024.05.30.md'
    - '2024.05.31.': 'scrums/2024.05.31.md'
  - Sprint: 
    - 'index': 'sprints/sprint_0.md'
    - '1회': 'sprints/sprint_1.md'
    - '2회': 'sprints/sprint_2.md'
    - '3회': 'sprints/sprint_3.md'
    - '4회': 'sprints/sprint_4.md'
    - '5회': 'sprints/sprint_5.md'
    - '6회': 'sprints/sprint_6.md'
    - '7회': 'sprints/sprint_7.md'
    - '8회': 'sprints/sprint_8.md'

theme:
  name: readthedocs
